language: node_js
node_js:
  - 14
before_install:
  - echo "before_install in build"
  - npm i -g npm@6.14.10
script: npm run lint && npm run test
branches:
  only:
    - master
env:
  variables:
    NODE_ENV: "development"
